## 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of modules and packages that provide pre-written code to perform common tasks, making it easier and faster to develop applications. We use Python libraries to avoid reinventing the wheel, to improve code efficiency, and to leverage the expertise encapsulated in these libraries for various functionalities such as numerical operations (NumPy), data manipulation (pandas), web development (Django), and more.

## 2. What is the difference between Numpy array and List?

Numpy Array: A NumPy array is a grid of values, all of the same type, indexed by a tuple of non-negative integers. It provides efficient storage and operations for large numerical datasets and supports vectorized operations, which are faster and more concise.

List: A Python list is a collection of elements that can be of different types. Lists are flexible and easy to use but are not optimized for numerical operations, making them slower for mathematical computations compared to NumPy arrays.


## 3. Find the shape, size, and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
#3 for getting the shape, size, dimmension of array
shape = arr.shape
size = arr.size   
dimension = arr.ndim

print(f'Shape of array: {shape}')
print(f'Size of array: {size}')
print(f'Dimmension of array: {dimension}')


Shape of array: (3, 4)
Size of array: 12
Dimmension of array: 2


## 4. Write Python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

## for getting first row
first_row = arr[0]
print(f'First row of array: {first_row}')

First row of array: [1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
## for accesing th element of third row and fourth column
element = arr[2,3]
print(f'Element of third row and fourth column: {element}')

Element of third row and fourth column: 12


## 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[::2,1::2]
print(f'Odd indexed element: \n{element}')

Odd indexed element: 
[[ 2  4]
 [10 12]]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [14]:
## import the required libraries
import numpy as np

## for generating random number of 3 x 3 matrix
arr = np.random.rand(3,3)

print(f'Random number :\n{arr}')

Random number :
[[0.91358912 0.01632546 0.43535982]
 [0.14330833 0.20918716 0.24515714]
 [0.6037552  0.57096489 0.95092722]]


## 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand: Generates random numbers in a given shape, uniformly distributed between 0 and 1.

np.random.randn: Generates random numbers in a given shape, normally distributed with mean 0 and standard deviation 1.

## 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
## for incresing the dimension
new_arr = arr[:, np.newaxis]
print(f'After increasing the dimension: \n{new_arr}')

After increasing the dimension: 
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


## 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
## import the required libraries
import numpy as np

## creating the numpy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
## for transposing the array
arr = arr.T
print(f'After transposing the array: \n{arr}')

After transposing the array: 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

#### 1.Index wise multiplication
#### 2.Matix multiplication
#### 3.Add both the maticx
#### 4.Subtact matix B from A
#### 5.Divide Matix B by A

In [19]:
Matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

Matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Element-wise multiplication
element_wise_mult = Matrix_A * Matrix_B

# Matrix multiplication
matrix_mult = np.dot(Matrix_A, Matrix_B.T)

# Addition of both matrices
addition = Matrix_A + Matrix_B

# Subtraction of Matrix B from Matrix A
subtraction = Matrix_A - Matrix_B

# Division of Matrix B by Matrix A
division = Matrix_B / Matrix_A

print(f'Elemen Wise multiplication: \n{element_wise_mult}')
print(f'Matrix multiplication: \n{matrix_mult}')
print(f'Addition of matices: \n{addition}')
print(f'Subtraction of matrices: \n{subtraction}')
print(f'Devision of matrices: \n{division}')


Elemen Wise multiplication: 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication: 
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of matices: 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of matrices: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Devision of matrices: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. Which function in NumPy can be used to swap the byte order of an array?

np.ndarray.byteswap()

## 13. What does the np.reshape function do, and how is it used?

In [21]:
reshaped_array = np.reshape(arr, (4, 3))
print(f'After reshaping the array: \n{reshaped_array}')


After reshaping the array: 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 14. What is the significance of the np.linalg.inv function?

## 15. What is broadcasting in NumPy?

Broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array so element-wise operations can be performed. This feature enables efficient computation without the need for explicit loops.